### ISSUE TITLE
大神，官方更新后，你怎么既保留新语法又吸收官方的新特性啊

### ISSUE THREAD

**Issue by SteveCruise** [frank198/pomelo-upgrade#1]
Rt~
你把语法更新了以后，然后网易官方又更新了一波新特性，你怎么既保留新语法又merge官方的新特性啊

**Comment by frank198** [comment]
官方的新特性 mqtt 性能更好一些。
可以使用 1.x 版本，添加了官方的新特性

**Comment by SteveCruise** [comment]
新版本还不依赖c++了
